### PR TITLE
Apply Google style to filename, include, header-guards

### PR DESCRIPTION
**Pull request by rakhimov**

### CODE REVIEW

**Comment by andrewprock** [comment]
Let's keep the class names and the file names aligned. Doing this creates multiple tokens for the same concept:

#include "card_distribution.h:
...
CardDistribution c;
...

**Comment by rakhimov** [comment]
> Let's keep the class names and the file names aligned. Doing this creates multiple tokens for the same concept:

C++ is not Java!

The current convention is just weird.

**Comment by andrew-ebss** [comment]
You should try coding in MFC ;)

**Comment by rakhimov** [comment]
> You should try coding in MFC ;)

Thanks, I am no masochist.

**Pull request closed without merging**
