### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by shindavid**
I noticed that when building on linux out-of-the-box, there were several (harmless) compiler warnings. This pull request simply removes those warnings.

One source of warnings comes from usage of the deprecated `std::binary_function` class, which I addressed with 3e292eea1f980ea0847febe4be88a1e63f47c8aa.

The other source of warnings comes from the fact that this project has a stale copy of the googletest/ repo. I addressed this by blowing away the existing googletest/ directory and copying googletest HEAD via the command,

```
git subtree add --prefix=src/ext/googletest https://github.com/google/googletest.git main --squash
```

Any future changes to googletest can be picked up by running:

```
git subtree pull --prefix=src/ext/googletest https://github.com/google/googletest.git main --squash
```

Given that googletest has adopted the [Abseil Live at Head philosophy](https://abseil.io/about/philosophy#upgrade-support), it should be safe to pick up future changes at any time.

`make && make test` passes on my Ubuntu desktop.

Feel free to disregard if there are some project nuances that make these changes nonviable.

### CODE REVIEW

**Comment by andrewprock** [comment]
The local version of google test is kept to ensure that upstream changes that google makes there do not affect this library. Happy to pick up the other changes in a PR.

**Comment by shindavid** [comment]
That is reasonable.

However, I'd like to note that `git subtree add` creates a hard local copy of the upstream repo, which is not unlike what this repo had before. This copy will never get updated unless someone explicitly invokes `git subtree pull` and then pushes that change to the repo. At worst, this pull request can be seen as a one-time refresh-to-head of src/googletest/ (validated by `make test`) with the option to easily do a controlled refresh at any point in the future.

Furthermore, by declaring adherence to the Abseil Live at Head philosophy, Google has made the promise that all future changes they make to googletest are guaranteed to either be (1) backwards-compatible, or (2) accompanied by automated refactoring tools, assuming that your project is using googletest in a "standard" way (which it appears to me to be the case).

With that said, if you still do not want the googletest change, I can create a new PR with just the other change.

**Comment by andrewprock** [comment]
Ok, that sounds reasonable. If you can separate this into two PRs (one for google test, the other for the rest) I'll merge them both.

**Comment by shindavid** [comment]
Great. Submitted two separate pull requests. Closing this one.

**Pull request closed without merging**
